// content/base/index.ts — TRESC BAZOWA jako PACZKA (dane), nie kod silnika (PLAN rozdz. 0, 3.2).
// Silnik nie zna tych bytow z nazwy — laduje je tym samym loaderem co DLC ("rdzen = konsument
// tego samego formatu co DLC"). Faza 1: dwa zasoby (cykle + dewizy), pelna drabina, ulepszenia,
// kamienie milowe. Liczby sa STARTOWE i strojone na zywo (PLAN 6.5, 20); ciag historyczny drabiny
// zachowany (PLAN 6.2). Odznaczenia (prestiz) sa zadeklarowane, ale zdobywa sie je dopiero w Fazie 2.
import type { Pack } from '@kombinat/shared';
import { buildAchievements } from './achievements';
import { buildEvents } from './events';
import { lateUpgrades } from './upgrades';
import { buildGeneratedUpgrades } from './genUpgrades';
import { buildMinigameUpgrades } from './genMinigame';
import { buildGeneratedTree } from './genTree';
import { buildGeneratedMilestones } from './genMilestones';

export const basePack: Pack = {
  manifest: {
    id: 'rdzen',
    name: 'Kombinat — rdzeń',
    version: '1.0.0',
    author: 'zespół',
    description: 'Bazowa ekonomia: drabina polskiej informatyki, dewizy i ulepszenia.',
    schemaVersion: 1,
    priority: 0,
    tags: ['rdzen'],
    visualIdentity: { accentColor: '#5fa86a', icon: null, font: null, texture: null },
  },

  resources: [
    {
      id: 'cykle',
      name: 'cykle',
      description: 'Cykle obliczeniowe — przerobione karty perforowane, listy płac, tablice dla GUS.',
      format: 'named',
      plural: { one: 'cykl', few: 'cykle', many: 'cykli', fractional: 'cykla' },
    },
    {
      id: 'dewizy',
      name: 'dewizy',
      description: 'Twarda waluta — bony Pewexu, zielone z kantoru. Rzadkie i strzeżone.',
      format: 'named',
      plural: { one: 'dewiza', few: 'dewizy', many: 'dewiz', fractional: 'dewizy' },
    },
    {
      id: 'odznaczenia',
      name: 'odznaczenia',
      description: 'Order Sztandaru Pracy i inne żetony zasług — waluta dziedzictwa (Denominacja).',
      format: 'named',
      plural: { one: 'odznaczenie', few: 'odznaczenia', many: 'odznaczeń', fractional: 'odznaczenia' },
      prestige: true,
    },
    // Waluty „uśpione" (uwaga #19) — zakodowane na przyszłe mechaniki, ukryte dopóki ich nie zdobędziesz.
    {
      id: 'bony',
      name: 'bony PEKAO',
      description: 'Bony towarowe Banku PEKAO — talony na towar z importu, obrót półlegalny.',
      format: 'named',
      plural: { one: 'bon', few: 'bony', many: 'bonów', fractional: 'bonu' },
      hidden: true,
    },
    {
      id: 'zlotowki',
      name: 'złotówki',
      description: 'Złoty polski — waluta codzienna, której zawsze za mało i zawsze nie na to.',
      format: 'named',
      plural: { one: 'złotówka', few: 'złotówki', many: 'złotówek', fractional: 'złotówki' },
      hidden: true,
    },
    {
      id: 'dolary',
      name: 'dolary',
      description: 'Zielone. Twarda waluta marzeń, spod lady i z Pewexu.',
      format: 'named',
      plural: { one: 'dolar', few: 'dolary', many: 'dolarów', fractional: 'dolara' },
      hidden: true,
    },
    // Towary reglamentowane (PLAN 9.1) — „waluty zastępcze" do smarowania. Ukryte, póki nie zaopatrzysz
    // się na czarnym rynku (kupno za dewizy). Łapówki w towarze są tańsze niż koperta z dewizami.
    {
      id: 'wodka',
      name: 'wódka',
      description: 'Półlitrówka — najtwardsza waluta PRL. Zachodnia whisky („Johnny") otwiera drzwi jeszcze szybciej.',
      format: 'named',
      plural: { one: 'butelka', few: 'butelki', many: 'butelek', fractional: 'butelki' },
      hidden: true,
      supply: { price: '18 + zasob.dewizy * 0.02', batch: 1 },
    },
    {
      id: 'kawa',
      name: 'kawa',
      description: 'Słoik rozpuszczalnej. W kraju, gdzie kawy ciągle brak, to gotówka na zapleczu.',
      format: 'named',
      plural: { one: 'słoik', few: 'słoiki', many: 'słoików', fractional: 'słoika' },
      hidden: true,
      supply: { price: '9 + zasob.dewizy * 0.015', batch: 1 },
    },
    {
      id: 'papierosy',
      name: 'papierosy',
      description: 'Karton zachodnich (Marlboro). Lepsze niż podanie z pieczątką.',
      format: 'named',
      plural: { one: 'karton', few: 'kartony', many: 'kartonów', fractional: 'kartonu' },
      hidden: true,
      supply: { price: '13 + zasob.dewizy * 0.02', batch: 1 },
    },
    {
      id: 'koniak',
      name: 'koniak',
      description: 'Flaszka francuskiego koniaku z Pewexu. Towar dla NAJWYŻSZYCH — drobnymi prezentami dygnitarza się nie kupi.',
      format: 'named',
      plural: { one: 'flaszka', few: 'flaszki', many: 'flaszek', fractional: 'flaszki' },
      hidden: true,
      supply: { price: '60 + zasob.dewizy * 0.05', batch: 1 },
    },
  ],

  generators: [
    {
      id: 'liczydlo',
      name: 'Liczydło',
      flavor: 'Drewno, druciki i palec wskazujący. Plan wykonany, choć kciuk boli.',
      costResource: 'cykle',
      cost: '15 * 1.15 ^ posiadane',
      outputResource: 'cykle',
      production: '0.2',
      accent: 'inherit',
    },
    {
      id: 'arytmometr',
      name: 'Arytmometr',
      flavor: 'Korbka i zębatki. Obsługuje go pan Kazimierz — jedyny, który wie, jak go nie zaciąć.',
      costResource: 'cykle',
      cost: '100 * 1.15 ^ posiadane',
      outputResource: 'cykle',
      production: '1',
      unlock: 'posiadane.liczydlo >= 1',
      accent: 'inherit',
    },
    {
      id: 'tabulator',
      name: 'Tabulator',
      flavor: 'Karta perforowana: dziurka to bit, brak dziurki też bit. Drugiej strony nikt nie sprawdza.',
      costResource: 'cykle',
      cost: '1100 * 1.15 ^ posiadane',
      outputResource: 'cykle',
      production: '8',
      unlock: 'posiadane.arytmometr >= 1',
      accent: 'inherit',
    },
    {
      id: 'mera400',
      name: 'MERA-400',
      flavor: 'Pierwszy sprzęt, który nie udaje. Liczy szybciej, niż magazyn wydaje części.',
      costResource: 'cykle',
      cost: '12000 * 1.15 ^ posiadane',
      outputResource: 'cykle',
      production: '47',
      unlock: 'posiadane.tabulator >= 1',
      accent: 'inherit',
    },
    {
      id: 'k202',
      name: 'K-202',
      flavor: 'Konstrukcja Karpińskiego biła Zachód. Biurokracja biła Karpińskiego. Zgadnij, kto wygrał.',
      costResource: 'cykle',
      cost: '130000 * 1.15 ^ posiadane',
      outputResource: 'cykle',
      production: '260',
      unlock: 'posiadane.mera400 >= 1',
      accent: 'inherit',
    },
    {
      id: 'odra1305',
      name: 'Odra 1305',
      flavor: 'Mainframe-robotnik z Elwro. Zgodny z ICL, bo blok lubił standaryzację.',
      costResource: 'cykle',
      cost: '1400000 * 1.15 ^ posiadane',
      outputResource: 'cykle',
      production: '1400',
      unlock: 'posiadane.k202 >= 1',
      accent: 'inherit',
    },
    {
      id: 'osrodek',
      name: 'Ośrodek obliczeniowy',
      flavor: 'Cała instytucja jako jeden generator. Etaty, kierownik i tabliczka „nieczynne do 14:00”.',
      costResource: 'cykle',
      cost: '20000000 * 1.15 ^ posiadane',
      outputResource: 'cykle',
      production: '7800',
      unlock: 'posiadane.odra1305 >= 1',
      accent: 'inherit',
    },
    {
      id: 'spectrum',
      name: 'ZX Spectrum + giełda',
      flavor: 'Import i kopiowanie gier na kasetach. Pierwsze prawdziwe dewizy spod lady.',
      costResource: 'cykle',
      cost: '330000000 * 1.15 ^ posiadane',
      outputResource: 'dewizy',
      production: '0.08',
      unlock: 'posiadane.osrodek >= 1',
      accent: 'inherit',
    },
    {
      id: 'meritum',
      name: 'Meritum / Elwro 800 Junior',
      flavor: 'Rodzimy komputer domowy. Junior dla szkół — w zasadzie klon Spectruma, ale „własny”.',
      costResource: 'dewizy',
      cost: '40 * 1.15 ^ posiadane',
      outputResource: 'cykle',
      production: '44000',
      unlock: 'posiadane.spectrum >= 1',
      accent: 'inherit',
    },
    {
      id: 'mazovia',
      name: 'Mazovia / klony PC',
      flavor: 'Przyszłość pełznąca do drzwi. Zgodna z IBM na tyle, na ile pozwala embargo.',
      costResource: 'dewizy',
      cost: '550 * 1.15 ^ posiadane',
      outputResource: 'cykle',
      production: '260000',
      unlock: 'posiadane.meritum >= 1',
      accent: 'inherit',
    },
    {
      id: 'spolka',
      name: 'Zalążek spółki / sieci',
      flavor: 'Nadchodzi 1989. Ktoś zakłada „spółkę z o.o.” i nikt już nie pyta o przydział.',
      costResource: 'dewizy',
      cost: '7500 * 1.15 ^ posiadane',
      outputResource: 'cykle',
      production: '1600000',
      unlock: 'posiadane.mazovia >= 1',
      accent: 'inherit',
    },
  ],

  upgrades: [
    {
      id: 'rdzen.u_wprawa',
      name: 'Wprawa operatora',
      flavor: 'Palec wyrobiony jak u maszynistki z biura przepustek.',
      costResource: 'cykle',
      cost: '100',
      once: true,
      effects: [{ type: 'addFlat', target: 'global', value: '4' }],
    },
    {
      id: 'rdzen.u_talon_czesci',
      name: 'Talon na części',
      flavor: 'Z talonem nawet śrubka jest osiągalna. Prawie.',
      costResource: 'cykle',
      cost: '500',
      unlock: 'posiadane.liczydlo >= 5',
      once: true,
      effects: [{ type: 'multiplyProduction', target: 'generator:liczydlo', value: '2' }],
    },
    {
      id: 'rdzen.u_przydzial',
      name: 'Przydział',
      flavor: 'Reglamentacja ma swoje plusy: w końcu coś przydzielają i Tobie.',
      costResource: 'cykle',
      cost: '6000',
      unlock: 'posiadane.arytmometr >= 5',
      once: true,
      effects: [{ type: 'multiplyProduction', target: 'generator:arytmometr', value: '2' }],
    },
    {
      id: 'rdzen.u_numer_bajtka',
      name: 'Numer Bajtka',
      flavor: 'Wiedza z kultowego magazynu (od 1985) = mnożnik. Przeczytaj, zanim sąsiad pożyczy.',
      costResource: 'cykle',
      cost: '75000',
      unlock: 'posiadane.tabulator >= 1',
      once: true,
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.25' }],
    },
    {
      id: 'rdzen.u_modyfikacja_mera',
      name: 'Modyfikacja sprzętu',
      flavor: 'Lutownica, odwaga i schemat z drugiej ręki. Gwarancja i tak nie obowiązuje.',
      costResource: 'cykle',
      cost: '400000',
      unlock: 'posiadane.mera400 >= 10',
      once: true,
      effects: [{ type: 'multiplyProduction', target: 'generator:mera400', value: '2' }],
    },
    {
      id: 'rdzen.u_przekupienie_magazyniera',
      name: 'Przekupienie magazyniera',
      flavor: 'Satyryczne „usprawnienie wydajności”. Kawa rozpuszczalna czyni cuda.',
      costResource: 'cykle',
      cost: '2000000',
      unlock: 'posiadane.k202 >= 1',
      once: true,
      effects: [{ type: 'divideCost', target: 'global', value: '1.5' }],
    },
    {
      id: 'rdzen.u_notatki_karpinskiego',
      name: 'Notatki Karpińskiego',
      flavor: 'Geniusz na papierze kratkowanym. Szkoda, że nie na linii produkcyjnej.',
      costResource: 'cykle',
      cost: '5000000',
      unlock: 'posiadane.k202 >= 5',
      once: true,
      effects: [{ type: 'multiplyProduction', target: 'generator:k202', value: '3' }],
    },
    {
      id: 'rdzen.u_standaryzacja',
      name: 'Standaryzacja ICL',
      flavor: 'Cały blok liczy tak samo. Przynajmniej taśmy pasują do każdego.',
      costResource: 'cykle',
      cost: '30000000',
      unlock: 'posiadane.odra1305 >= 5',
      once: true,
      effects: [{ type: 'multiplyProduction', target: 'generator:odra1305', value: '2' }],
    },
    {
      id: 'rdzen.u_bony_pewex',
      name: 'Bony z Pewexu',
      flavor: 'Twarda waluta lubi się mnożyć, gdy nikt nie patrzy.',
      costResource: 'dewizy',
      cost: '100',
      unlock: 'posiadane.spectrum >= 1',
      once: true,
      effects: [{ type: 'multiplyProduction', target: 'resource:dewizy', value: '2' }],
    },
    {
      id: 'rdzen.u_demoscena',
      name: 'Wschodnia demoscena',
      flavor: 'Gówniarze z demosceny robią cuda w 4 kilobajtach. I w Twoim kombinacie.',
      costResource: 'dewizy',
      cost: '1000',
      unlock: 'posiadane.meritum >= 1',
      once: true,
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.5' }],
    },
    {
      id: 'rdzen.u_magnetofon',
      name: 'Magnetofon Kasprzak',
      flavor: 'Wczytywanie gier z taśmy to sztuka i hazard. Odblokowuje minigrę „Taśma".',
      costResource: 'dewizy',
      cost: '300',
      unlock: 'posiadane.spectrum >= 1',
      once: true,
      effects: [{ type: 'enableMechanic', mechanic: 'minigra_tasma' }],
    },
    ...lateUpgrades,
    // Generowane ulepszenia (U1/U2, docs/ULEPSZENIA.md) — rodziny drabin per maszyna, globalne, koszty,
    // klikanie, dewizy, „filar". Bramkowane progresją, by late game miał ciągłą podaż.
    ...buildGeneratedUpgrades(),
    // Ulepszenia ZA GRANIE (U4) — bramkowane licznikami minigier (Taśma/Kantor/Załatwianie/Okazje).
    ...buildMinigameUpgrades(),
  ],

  milestones: [
    {
      id: 'rdzen.m_pierwsza_setka',
      name: 'Pierwsza setka',
      trigger: 'posiadane.liczydlo >= 100',
      effects: [{ type: 'multiplyProduction', target: 'generator:liczydlo', value: '2' }],
    },
    {
      id: 'rdzen.m_era_kart',
      name: 'Era kart',
      trigger: 'posiadane.tabulator >= 25',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.1' }],
    },
    {
      id: 'rdzen.m_pierwsze_dewizy',
      name: 'Pierwsze dewizy',
      trigger: 'zasob.dewizy >= 1',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.05' }],
    },
    {
      id: 'rdzen.m_instytucja',
      name: 'Instytucja',
      trigger: 'posiadane.osrodek >= 10',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.2' }],
    },
    {
      id: 'rdzen.m_kontrakt_eksportowy',
      name: 'Kontrakt eksportowy',
      trigger: 'posiadane.spectrum >= 10',
      effects: [{ type: 'multiplyProduction', target: 'resource:dewizy', value: '1.5' }],
    },
    {
      id: 'rdzen.m_sto_odr',
      name: 'Sto Odr',
      trigger: 'posiadane.odra1305 >= 100',
      effects: [{ type: 'multiplyProduction', target: 'generator:odra1305', value: '3' }],
    },
    // Talon na samochód (PLAN 9.1) — reglamentowany przydział na rzeczy wielkie. Po wielu załatwieniach
    // „trafia" Ci się talon: legendarny mały kamień milowy z trwałym bonusem do całej produkcji.
    {
      id: 'rdzen.m_talon_samochod',
      name: 'Talon na samochód',
      trigger: 'licznik.lapowki >= 12',
      effects: [
        { type: 'multiplyProduction', target: 'global', value: '1.3' },
        { type: 'multiplyProduction', target: 'resource:dewizy', value: '1.2' },
      ],
    },
    // Pierwszy Zjazd PZPR (Faza 4B) — kamień milowy po pierwszym wyborze doktryny; odblokowuje też
    // hasła Leksykonu o polityce epoki (Zjazd, dekada Gierka).
    {
      id: 'rdzen.m_zjazd',
      name: 'Pierwszy Zjazd',
      trigger: 'licznik.zjazdy >= 1',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.05' }],
    },
    // Masowo generowane kamienie milowe (U5, docs/ULEPSZENIA.md) — drabiny progów (park maszyn, bank
    // cykli/dewiz, „za granie", prestiż), nadają trwały mały bonus po osiągnięciu. Domknięcie liczby ≥1000.
    ...buildGeneratedMilestones(),
  ],

  // Osiagniecia (PLAN 8.3) — generowane masowo (300+), to wciaz dane. Mnozniki aktywne dopiero po
  // wezle drzewa „Tablica wyroznien” (retroaktywnie).
  achievements: buildAchievements(),

  // Drzewo dziedzictwa (PLAN 7) — kupowane za odznaczenia, TRWALE (przezywaja Denominacje). TRZY KONARY
  // (kolumny), kazdy to RODZINA wezlow wymagajaca SIEBIE PO KOLEI (lancuch): Aparat / Rodzime R&D /
  // Rynek. Na koncu zwornik „Order” wymaga konca wszystkich trzech konarow. Late-game wezly na dole.
  treeNodes: [
    // === KONAR I — APARAT (biurokracja, produkcja globalna) ===
    {
      id: 'rdzen.t_teczka',
      name: 'Teczka kadrowa',
      description: 'Twoje akta. Od czegoś trzeba zacząć karierę w aparacie.',
      cost: '2',
      requires: [],
      branch: 'aparat',
      kind: 'gate',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.1' }],
    },
    {
      id: 'rdzen.t_etat',
      name: 'Dodatkowy etat',
      description: 'Jeden etat więcej. Pracować będzie ktoś inny.',
      cost: '4',
      requires: ['rdzen.t_teczka'],
      branch: 'aparat',
      levels: 2,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.25' }],
    },
    {
      id: 'rdzen.t_premia',
      name: 'Premia kwartalna',
      description: 'Za wykonanie planu, którego i tak nikt nie sprawdzi.',
      cost: '9',
      requires: ['rdzen.t_etat'],
      branch: 'aparat',
      levels: 3,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.4' }],
    },
    {
      id: 'rdzen.t_tablica',
      name: 'Tablica wyróżnień',
      description:
        'Każde zdobyte osiągnięcie mnoży produkcję — także te sprzed lat. Każdy poziom dokłada dodatkowy mnożnik.',
      cost: '17',
      requires: ['rdzen.t_premia'],
      branch: 'aparat',
      levels: 4,
      kind: 'enableAchievementMultipliers',
      effects: [
        { type: 'enableAchievementMultipliers' },
        { type: 'multiplyProduction', target: 'global', value: '1.2' },
      ],
    },
    {
      id: 'rdzen.t_plan',
      name: 'Napięty plan',
      description: 'Produkcja w górę — ale i koszty rosną. Tak się buduje socjalizm.',
      cost: '32',
      requires: ['rdzen.t_tablica'],
      branch: 'aparat',
      levels: 5,
      kind: 'keystone',
      effects: [
        { type: 'multiplyProduction', target: 'global', value: '1.5' },
        { type: 'multiplyCost', target: 'global', value: '1.15' },
      ],
    },
    {
      id: 'rdzen.t_nomenklatura',
      name: 'Nomenklatura',
      description: 'Lojalni ludzie na właściwych stołkach. Cała machina kręci się dla Ciebie.',
      cost: '64',
      requires: ['rdzen.t_plan'],
      branch: 'aparat',
      levels: 6,
      kind: 'keystone',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.45' }],
    },

    // === KONAR II — RODZIME R&D (laboratorium, maszyny, start) ===
    {
      id: 'rdzen.t_lab',
      name: 'Własne laboratorium',
      description: 'Lutownica, oscyloskop i zapał. Reszta sama się złoży.',
      cost: '2',
      requires: [],
      branch: 'rd',
      kind: 'gate',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.2' }],
    },
    {
      id: 'rdzen.t_karpinski',
      name: 'Szkoła Karpińskiego',
      description: 'Genialne konstrukcje — tym razem ktoś ich posłucha.',
      cost: '4',
      requires: ['rdzen.t_lab'],
      branch: 'rd',
      levels: 2,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'generator:k202', value: '2' }],
    },
    {
      id: 'rdzen.t_palce',
      name: 'Wprawne palce',
      description: 'Lata przy klawiaturze robią swoje.',
      cost: '9',
      requires: ['rdzen.t_karpinski'],
      branch: 'rd',
      levels: 3,
      kind: 'multiplier',
      effects: [{ type: 'addFlat', target: 'global', value: '25' }],
    },
    {
      id: 'rdzen.t_elwro',
      name: 'Tradycja Elwro',
      description: 'Wrocław liczy od dekad i liczyć nie przestanie.',
      cost: '17',
      requires: ['rdzen.t_palce'],
      branch: 'rd',
      levels: 4,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'generator:odra1305', value: '1.6' }],
    },
    {
      id: 'rdzen.t_zapas',
      name: 'Zapas magazynowy',
      description: 'Coś tam zawsze leży „na czarną godzinę”. Teraz to Twój start.',
      cost: '32',
      requires: ['rdzen.t_elwro'],
      branch: 'rd',
      levels: 5,
      kind: 'start',
      effects: [
        { type: 'startWith', target: 'generator:liczydlo', value: '25' },
        { type: 'startWith', target: 'generator:arytmometr', value: '10' },
      ],
    },
    {
      id: 'rdzen.t_instytut',
      name: 'Instytut badawczy',
      description: 'Własny instytut z budżetem i halą maszyn. Rodzima myśl techniczna w natarciu.',
      cost: '64',
      requires: ['rdzen.t_zapas'],
      branch: 'rd',
      levels: 6,
      kind: 'keystone',
      effects: [
        { type: 'multiplyProduction', target: 'generator:k202', value: '1.5' },
        { type: 'multiplyProduction', target: 'generator:odra1305', value: '1.4' },
      ],
    },

    // === KONAR III — RYNEK (dewizy, giełda, start gotówkowy) ===
    {
      id: 'rdzen.t_kantor',
      name: 'Stały kantor',
      description: 'Zawsze ktoś chętny do wymiany. Kurs „przyjacielski”.',
      cost: '2',
      requires: [],
      branch: 'rynek',
      kind: 'gate',
      effects: [{ type: 'multiplyProduction', target: 'resource:dewizy', value: '2' }],
    },
    {
      id: 'rdzen.t_bony',
      name: 'Zapas bonów',
      description: 'Garść bonów Pewexu na nowy początek.',
      cost: '4',
      requires: ['rdzen.t_kantor'],
      branch: 'rynek',
      levels: 2,
      kind: 'start',
      effects: [{ type: 'startWith', target: 'resource:dewizy', value: '50' }],
    },
    {
      id: 'rdzen.t_zaliczka',
      name: 'Zaliczka na poczet planu',
      description: 'Trochę cykli na rozruch nowej pięciolatki.',
      cost: '9',
      requires: ['rdzen.t_bony'],
      branch: 'rynek',
      levels: 3,
      kind: 'start',
      effects: [{ type: 'startWith', target: 'resource:cykle', value: '1000' }],
    },
    {
      id: 'rdzen.t_gielda',
      name: 'Przeczucie giełdowe',
      description: 'Kupować, gdy tanio. Sprzedawać, gdy drożej. Ktoś musi.',
      cost: '17',
      requires: ['rdzen.t_zaliczka'],
      branch: 'rynek',
      levels: 4,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.35' }],
    },
    {
      id: 'rdzen.t_spekulant',
      name: 'Zawodowy spekulant',
      description: 'Kursy czujesz nosem. Dewizy mnożą się szybciej, niż państwo zdąży je policzyć.',
      cost: '32',
      requires: ['rdzen.t_gielda'],
      branch: 'rynek',
      levels: 5,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'resource:dewizy', value: '1.5' }],
    },
    {
      id: 'rdzen.t_holding',
      name: 'Holding',
      description: 'Sieć spółek, w której nikt już nie wie, kto do kogo należy. Poza Tobą.',
      cost: '64',
      requires: ['rdzen.t_spekulant'],
      branch: 'rynek',
      levels: 6,
      kind: 'keystone',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.4' }],
    },

    // === GŁĘBSZE WĘZŁY (Faza szlifu) — dawne „zworniki" wpięte W KONARY + nowe ulepszenia, by drzewo
    // ciągnęło się dłużej i „nie kończyło". Każdy konar idzie dalej; „Order" to wielki finał na końcu
    // Aparatu, wymagający dorobku we WSZYSTKICH trzech konarach. Koszt rośnie ×2 z poziomem (grind). ===
    // -- Aparat (dalej) --
    {
      id: 'rdzen.t_druga_gospodarka',
      name: 'Druga gospodarka',
      description: 'Oficjalnie nie istnieje, a kręci pół kraju. Im głębiej w drugim obiegu, tym sprawniej idzie wszystko.',
      cost: '90',
      requires: ['rdzen.t_nomenklatura'],
      branch: 'aparat',
      levels: 7,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.15' }],
    },
    {
      id: 'rdzen.t_aparatczyk',
      name: 'Aparatczyk doskonały',
      description: 'Wiesz, komu podziękować i kogo nie zauważyć. Cała machina państwowa pracuje na Twoje słupki.',
      cost: '140',
      requires: ['rdzen.t_druga_gospodarka'],
      branch: 'aparat',
      levels: 8,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.3' }],
    },
    {
      id: 'rdzen.t_centrala',
      name: 'Centrala planowania',
      description: 'Twoje wykresy w Komisji Planowania stają się prawem. Plan wreszcie zgadza się z życzeniem.',
      cost: '200',
      requires: ['rdzen.t_aparatczyk'],
      branch: 'aparat',
      levels: 9,
      kind: 'keystone',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.4' }],
    },
    // -- Rodzime R&D (dalej) --
    {
      id: 'rdzen.t_mikrokomputer',
      name: 'Mikrokomputer domowy',
      description: 'Meritum i klony ZX trafiają pod strzechy. Pół kraju programuje po godzinach.',
      cost: '90',
      requires: ['rdzen.t_instytut'],
      branch: 'rd',
      levels: 7,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'generator:spectrum', value: '1.7' }],
    },
    {
      id: 'rdzen.t_demoscena',
      name: 'Polska demoscena',
      description: 'Nastolatki wyciskają z ośmiu bitów cuda, jakich Zachód nie widział. Myśl techniczna kwitnie.',
      cost: '140',
      requires: ['rdzen.t_mikrokomputer'],
      branch: 'rd',
      levels: 8,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.3' }],
    },
    {
      id: 'rdzen.t_dolina',
      name: 'Dolina nad Wisłą',
      description: 'Garażowe spółki, genialni inżynierowie, eksport myśli. Krzemowa legenda — tyle że szara.',
      cost: '200',
      requires: ['rdzen.t_demoscena'],
      branch: 'rd',
      levels: 9,
      kind: 'keystone',
      effects: [
        { type: 'multiplyProduction', target: 'global', value: '1.35' },
        { type: 'multiplyProduction', target: 'generator:odra1305', value: '1.5' },
      ],
    },
    // -- Rynek (dalej) --
    {
      id: 'rdzen.t_attache',
      name: 'Attaché handlowy',
      description: 'Twój człowiek przy każdej delegacji. Relacje zacieśniają się szybciej — każdy poziom dokłada do kroku.',
      cost: '90',
      requires: ['rdzen.t_holding'],
      branch: 'rynek',
      levels: 7,
      kind: 'multiplier',
      effects: [{ type: 'diplomacyStep', value: '2' }],
    },
    {
      id: 'rdzen.t_cinkciarz',
      name: 'Król cinkciarzy',
      description: 'Cały plac pod Pewexem pracuje dla Ciebie. Kurs ustalasz Ty, nie NBP.',
      cost: '140',
      requires: ['rdzen.t_attache'],
      branch: 'rynek',
      levels: 8,
      kind: 'multiplier',
      effects: [{ type: 'multiplyProduction', target: 'resource:dewizy', value: '1.5' }],
    },
    {
      id: 'rdzen.t_offshore',
      name: 'Konto na Zachodzie',
      description: 'Część obrotu „znika" za granicą i wraca jako czysty zysk. Druga gospodarka ma drugie dno.',
      cost: '200',
      requires: ['rdzen.t_cinkciarz'],
      branch: 'rynek',
      levels: 9,
      kind: 'keystone',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.4' }],
    },
    // -- Finały konarów (rząd 10) — po 10 poziomów każdy, symetrycznie w każdym konarze. „Order" to
    // wielki finał Aparatu, wymagający dorobku we WSZYSTKICH trzech konarach; R&D i Rynek mają własne
    // zwieńczenia, by kolumny były równej długości. Od nich startują „nieskończone" ogony (genTree). --
    {
      id: 'rdzen.t_order',
      name: 'Order Sztandaru Pracy',
      description: 'Najwyższe wyróżnienie. Wisi, błyszczy i mnoży wszystko — poziom po poziomie — gdy zbudujesz potęgę we WSZYSTKICH trzech konarach.',
      cost: '10000',
      requires: ['rdzen.t_centrala', 'rdzen.t_dolina', 'rdzen.t_offshore'],
      branch: 'aparat',
      fogged: true,
      levels: 10,
      kind: 'keystone',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '1.4' }],
    },
    {
      id: 'rdzen.t_fin_rd',
      name: 'Krzemowy szczyt',
      description: 'Rodzima myśl techniczna sięga absolutu. Każdy poziom odrywa naukę od reszty świata — bez końca.',
      cost: '10000',
      requires: ['rdzen.t_dolina'],
      branch: 'rd',
      fogged: true,
      levels: 10,
      kind: 'keystone',
      effects: [
        { type: 'multiplyProduction', target: 'global', value: '1.3' },
        { type: 'multiplyProduction', target: 'generator:odra1305', value: '1.4' },
      ],
    },
    {
      id: 'rdzen.t_fin_rynek',
      name: 'Wielka prywatyzacja',
      description: 'Druga gospodarka wychodzi z cienia i przejmuje pierwszą. Kapitał pracuje sam na siebie — poziom po poziomie.',
      cost: '10000',
      requires: ['rdzen.t_offshore'],
      branch: 'rynek',
      fogged: true,
      levels: 10,
      kind: 'keystone',
      effects: [
        { type: 'multiplyProduction', target: 'resource:dewizy', value: '1.4' },
        { type: 'multiplyProduction', target: 'global', value: '1.2' },
      ],
    },
    // Głębokie „nieskończone" ogony konarów (U3, docs/ULEPSZENIA.md) — zamglone, odsłaniają się po kolei;
    // poziomy rosną w głąb. Aparat startuje PO „Order", R&D po „Dolinie", Rynek po „Koncie na Zachodzie".
    ...buildGeneratedTree(),
  ],

  // Zdarzenia (PLAN 8.4) — modalne mini-historyjki: story-beaty (once) + losowe (weight) + lancuch SB.
  // Kwoty skalowane procentem stanu, by mialy znaczenie i wczesnie, i pozno (PLAN 6.5).
  events: buildEvents(),

  ticker: [
    { id: 'rdzen.tick_plan', stream: 'propaganda', text: 'Towarzysze, wykonanie planu w 143%! Pozostałe 57% to oczywiście błąd statystyczny.' },
    { id: 'rdzen.tick_pewex', stream: 'notice', text: 'W Pewexie rzucili Atari. Kolejka od wczoraj. Stoi też towarzysz dyrektor, ale incognito.' },
    { id: 'rdzen.tick_karta', stream: 'advice', text: 'Porada dnia: kartę perforowaną można odwrócić. Drugiej strony i tak nikt nie sprawdza.' },
    { id: 'rdzen.tick_erewan', stream: 'easter', text: 'Radio Erewań pyta: czy komputer zastąpi człowieka? Odpowiadamy: tylko w kolejce.' },
    { id: 'rdzen.tick_norma', stream: 'advice', text: 'Porada: klikanie liczy się wcześnie. Później maszyny przejmą normę.' },
    { id: 'rdzen.tick_dewizy', stream: 'propaganda', text: 'Bilans handlowy dodatni — pod warunkiem nieuwzględniania importu.' },
    { id: 'rdzen.tick_kantor', stream: 'notice', text: 'Cinkciarz spod Forum oferuje kurs „przyjacielski”. Dla każdego inny, ale przyjacielski.' },
    { id: 'rdzen.tick_kaseta', stream: 'easter', text: 'Kaseta wczytuje się 4 minuty. W połowie ktoś włącza suszarkę i trzeba od nowa.' },
    { id: 'rdzen.tick_5lat', stream: 'propaganda', text: 'Plan pięcioletni wykonano w cztery lata. Piąty rok przeznaczono na świętowanie.' },
    { id: 'rdzen.tick_buty', stream: 'propaganda', text: 'Produkcja butów wzrosła o 200%. Niestety wyłącznie lewych.' },
    { id: 'rdzen.tick_nigdy', stream: 'propaganda', text: 'Nigdy nie było tak dobrze. Źródła historyczne są w przygotowaniu.' },
    { id: 'rdzen.tick_wskazniki', stream: 'propaganda', text: 'Towarzysze, wskaźniki rosną. Które dokładnie — to tajemnica państwowa.' },
    { id: 'rdzen.tick_remont', stream: 'propaganda', text: 'Wczoraj oddano do użytku nowy ośrodek. Dziś już go remontują — oto dynamika.' },
    { id: 'rdzen.tick_eksport2', stream: 'propaganda', text: 'Eksport pomyślny. Importu, dla zachowania równowagi, nie odnotowano.' },
    { id: 'rdzen.tick_uderz', stream: 'advice', text: 'Porada: jeśli maszyna nie działa — uderz ją. Jeśli działa — pod żadnym pozorem nie dotykaj.' },
    { id: 'rdzen.tick_okazja', stream: 'advice', text: 'Porada: brak części zamiennych to nie problem, lecz okazja do wykazania się.' },
    { id: 'rdzen.tick_kolejka', stream: 'advice', text: 'Porada: kolejkę najlepiej zająć wczoraj.' },
    { id: 'rdzen.tick_podanie', stream: 'advice', text: 'Porada: do każdego podania dołącz drugie — o rozpatrzenie pierwszego.' },
    { id: 'rdzen.tick_dyskietka', stream: 'advice', text: 'Porada: dyskietkę można przedziurkować, by zrobić z niej dwie. Tak przynajmniej mówią.' },
    { id: 'rdzen.tick_realnosc', stream: 'advice', text: 'Porada: jeśli plan jest nierealny, zmień realność — nie plan.' },
    { id: 'rdzen.tick_norma2', stream: 'advice', text: 'Porada: norma wykonana przed czasem to norma źle ustawiona. Na przyszłość.' },
    { id: 'rdzen.tick_erewan2', stream: 'easter', text: 'Radio Erewań pyta: czy można zbudować socjalizm w jednym kraju? Można, ale lepiej mieszkać w innym.' },
    { id: 'rdzen.tick_erewan3', stream: 'easter', text: 'Radio Erewań pyta: jaka jest różnica między planem a prognozą pogody? Prognoza czasem się sprawdza.' },
    { id: 'rdzen.tick_nadgorliwy', stream: 'easter', text: 'Plotka: w pewnym ośrodku komputer sam wykonał plan. Zwolniono go za nadgorliwość.' },
    { id: 'rdzen.tick_instrukcja', stream: 'easter', text: 'Mówią, że jeden inżynier zrozumiał instrukcję obsługi. Zabrali go do Warszawy.' },
    { id: 'rdzen.tick_biurko', stream: 'easter', text: 'Podobno na Zachodzie komputer mieści się na biurku. U nas też — po wyniesieniu biurka.' },
    { id: 'rdzen.tick_dzinsy', stream: 'notice', text: 'W Pewexie rzucili dżinsy. Rozmiar jeden, uniwersalny — dla każdego odrobinę za ciasny.' },
    { id: 'rdzen.tick_dziurki', stream: 'notice', text: 'Uwaga: dostawa kart perforowanych opóźniona. Powód: zabrakło dziurek.' },
    { id: 'rdzen.tick_winda', stream: 'notice', text: 'Komunikat: winda w gmachu nieczynna. Schody również — ale z zupełnie innego powodu.' },
    { id: 'rdzen.tick_kurs', stream: 'notice', text: 'Cinkciarz pod Forum podniósł kurs. Twierdzi, że to przez napięcie międzynarodowe.' },
    { id: 'rdzen.tick_magazyn', stream: 'notice', text: 'Magazyn czynny w godzinach, w których i tak nikogo nie ma.' },
    { id: 'rdzen.tick_prad', stream: 'notice', text: 'Uwaga: prąd wyłączany planowo i nieplanowo, naprzemiennie. Dla pewności.' },
    { id: 'rdzen.tick_talon2', stream: 'notice', text: 'Talon na samochód przyznany. Odbiór za 11 lat — prosimy nie dzwonić w tej sprawie.' },
  ],

  lexicon: [
    {
      id: 'rdzen.lex_k202',
      name: 'K-202',
      unlockedBy: 'generator:k202',
      text: 'K-202 to minikomputer Jacka Karpińskiego z początku lat 70. Konstrukcyjnie wyprzedzał wiele maszyn Zachodu, a mimo to produkcję zdławiły rozgrywki biurokratyczno-polityczne. Klasyczne „co by było, gdyby” polskiej informatyki.',
    },
    {
      id: 'rdzen.lex_spectrum',
      name: 'ZX Spectrum w Polsce',
      unlockedBy: 'generator:spectrum',
      text: 'ZX Spectrum był w latach 80. najpopularniejszym domowym komputerem w Polsce. Wokół niego wyrósł nieformalny rynek kopiowania gier na kasetach magnetofonowych — i giełdy komputerowe, gdzie handlowano sprzętem i oprogramowaniem.',
    },
    {
      id: 'rdzen.lex_meritum',
      name: 'Elwro 800 Junior',
      unlockedBy: 'generator:meritum',
      text: 'Elwro 800 Junior to polski komputer szkolny z końca lat 80., zgodny programowo z ZX Spectrum. Miał skomputeryzować szkoły rodzimym sprzętem — w praktyce był klonem popularnej maszyny Sinclaira.',
    },
    {
      id: 'rdzen.lex_mera400',
      name: 'MERA-400',
      unlockedBy: 'generator:mera400',
      text: 'MERA-400 to polski minikomputer z lat 70. produkowany przez zakłady ERA, stosowany m.in. w przemyśle i nauce. Jeden z bardziej udanych krajowych projektów tej klasy.',
    },
    {
      id: 'rdzen.lex_osrodek',
      name: 'Ośrodki obliczeniowe',
      unlockedBy: 'generator:osrodek',
      text: 'W PRL drogie maszyny skupiano w zakładowych i resortowych ośrodkach obliczeniowych — z operatorami, kartami zleceń i kolejką zadań. Komputer był instytucją, nie sprzętem na biurko.',
    },
    {
      id: 'rdzen.lex_mazovia',
      name: 'Mazovia',
      unlockedBy: 'generator:mazovia',
      text: 'Mazovia to polski klon IBM PC/XT z końca lat 80. — próba dogonienia standardu PC mimo embarga CoCom ograniczającego dostęp do zachodnich podzespołów.',
    },
    {
      id: 'rdzen.lex_bajtek',
      name: 'Bajtek',
      unlockedBy: 'event:rdzen.ev_bajtek',
      text: 'Bajtek — wydawany od 1985 popularny magazyn komputerowy. Dla wielu czytelników był pierwszym źródłem wiedzy o programowaniu, sprzęcie i grach.',
    },
    {
      id: 'rdzen.lex_pewex',
      name: 'Pewex',
      unlockedBy: 'event:rdzen.ev_c_pewex',
      text: 'Pewex — sieć sklepów sprzedających towary za waluty wymienialne i bony. W realiach niedoboru symbol „lepszego świata” dostępnego za zielone.',
    },
    {
      id: 'rdzen.lex_zalatwianie',
      name: 'Załatwianie',
      unlockedBy: 'generator:mera400',
      icon: 'handshake',
      text: 'Gospodarka oficjalna była fikcją — naprawdę wszystko działało przez „załatwianie”: po znajomości, spod lady, po blacie. Nie korupcja od święta, lecz codzienny sposób, w jaki dostawało się to, czego oficjalnie „nie ma”.',
    },
    {
      id: 'rdzen.lex_kartki',
      name: 'Kartki i towar reglamentowany',
      unlockedBy: 'generator:mera400',
      icon: 'ticket',
      text: 'Wobec chronicznych niedoborów wiele towarów było na kartki (mięso, cukier, benzyna). Realnymi „walutami zastępczymi” łapówki bywały butelka wódki czy whisky („Johnny”), kawa, zachodnie papierosy (Marlboro) — twardsze niż złotówka.',
    },
    {
      id: 'rdzen.lex_cinkciarz',
      name: 'Cinkciarz',
      unlockedBy: 'generator:spectrum',
      icon: 'dollar',
      text: 'Cinkciarz to uliczny handlarz walutą — skupował i sprzedawał dewizy po kursie czarnorynkowym, dużo korzystniejszym niż oficjalny. Półlegalna, wszechobecna instytucja PRL-owskiego kantoru „pod Forum”.',
    },
    {
      id: 'rdzen.lex_talon',
      name: 'Talon na samochód',
      unlockedBy: 'milestone:rdzen.m_talon_samochod',
      icon: 'car',
      text: 'Na rzeczy wielkie (samochód, mieszkanie) dostawało się reglamentowany przydział — talon. Legendarny „talon na malucha” oznaczał często wieloletnie oczekiwanie; prawo do niego samo w sobie stawało się towarem na sprzedaż.',
    },
    {
      id: 'rdzen.lex_zjazd',
      name: 'Zjazd PZPR',
      unlockedBy: 'milestone:rdzen.m_zjazd',
      icon: 'landmark',
      text: 'Zjazd Polskiej Zjednoczonej Partii Robotniczej — najwyższe wydarzenie polityczne, na którym wytyczano „linię” na kolejne lata. Uchwały Zjazdu spinały się z rytmem pięciolatek i wyznaczały, co i jak ma się produkować.',
    },
    {
      id: 'rdzen.lex_gierek',
      name: 'Dekada Gierka',
      unlockedBy: 'milestone:rdzen.m_zjazd',
      icon: 'trending-up',
      text: 'Lata 70. pod wodzą Edwarda Gierka: boom napędzany zachodnimi kredytami, hasło „Polska rośnie w siłę, a ludziom żyje się dostatniej” i „propaganda sukcesu”. Rachunek przyszedł później — bomba zadłużenia wybuchła kryzysem przełomu dekad.',
    },
  ],

  // Kadra (PLAN 18 — „kadra/postacie”): werbunek za zasoby, pasywne bonusy PER ROZGRYWKA (znikają po
  // Denominacji, jak ulepszenia). Każdy to archetyp epoki — od cynicznego inżyniera po cinkciarza.
  characters: [
    {
      id: 'rdzen.kadra_inzynier',
      name: 'Cyniczny inżynier',
      archetype: 'Konstruktor',
      flavor: 'Wszystko już widział. Naprawi każdą maszynę, ale najpierw powie, że to i tak nie ma sensu.',
      costResource: 'cykle',
      cost: '60000',
      unlock: 'posiadane.mera400 >= 1',
      passive: [{ type: 'multiplyProduction', target: 'global', value: '1.15' }],
    },
    {
      id: 'rdzen.kadra_zalatwiacz',
      name: 'Partyjny załatwiacz',
      archetype: 'Aparat',
      flavor: 'Zna kogoś, kto zna kogoś. Części pojawiają się jakby spod ziemi — i taniej.',
      costResource: 'cykle',
      cost: '4000000',
      unlock: 'posiadane.osrodek >= 1',
      passive: [{ type: 'divideCost', target: 'global', value: '1.3' }],
    },
    {
      id: 'rdzen.kadra_aparatczyk',
      name: 'Towarzysz dyrektor',
      archetype: 'Aparat',
      flavor: 'Plan wykonany, zanim go ogłoszono. Wskaźniki rosną już na sam jego widok.',
      costResource: 'cykle',
      cost: '40000000',
      unlock: 'posiadane.odra1305 >= 5',
      passive: [{ type: 'multiplyProduction', target: 'global', value: '1.3' }],
    },
    {
      id: 'rdzen.kadra_cinkciarz',
      name: 'Cinkciarz spod Forum',
      archetype: 'Rynek',
      flavor: 'Kurs zawsze przyjacielski. Dewizy mnożą się w jego rękach szybciej niż w banku narodowym.',
      costResource: 'dewizy',
      cost: '60',
      unlock: 'posiadane.spectrum >= 1',
      passive: [{ type: 'multiplyProduction', target: 'resource:dewizy', value: '1.5' }],
    },
    {
      id: 'rdzen.kadra_demoscena',
      name: 'Gówniarz z demosceny',
      archetype: 'Rynek',
      flavor: 'Robi cuda w czterech kilobajtach. Klika tak szybko, że klawiatura prosi o litość.',
      costResource: 'dewizy',
      cost: '250',
      unlock: 'posiadane.meritum >= 1',
      passive: [
        { type: 'addFlat', target: 'global', value: '60' },
        { type: 'multiplyProduction', target: 'global', value: '1.2' },
      ],
    },
    // Więcej kadry (U5) — kolejne archetypy epoki do werbunku (per rozgrywka).
    {
      id: 'rdzen.kadra_spawacz',
      name: 'Spawacz-racjonalizator',
      archetype: 'Konstruktor',
      flavor: 'Ma patent na wszystko i skrzynkę pomysłów pełną po brzegi. Norma drży na sam jego widok.',
      costResource: 'cykle',
      cost: '900000',
      unlock: 'posiadane.tabulator >= 5',
      passive: [{ type: 'multiplyProduction', target: 'global', value: '1.18' }],
    },
    {
      id: 'rdzen.kadra_ksiegowa',
      name: 'Księgowa kreatywna',
      archetype: 'Aparat',
      flavor: 'Bilans zawsze się zgadza — z tym, co ma się zgadzać. Dewizy znajdują się same.',
      costResource: 'dewizy',
      cost: '120',
      unlock: 'posiadane.spectrum >= 1',
      passive: [{ type: 'multiplyProduction', target: 'resource:dewizy', value: '1.4' }],
    },
    {
      id: 'rdzen.kadra_magazynier',
      name: 'Magazynier z drugiego obiegu',
      archetype: 'Rynek',
      flavor: 'Czego nie ma w magazynie, to ma „na zapleczu". Części tanieją, gdy podaje rękę.',
      costResource: 'cykle',
      cost: '8000000',
      unlock: 'posiadane.k202 >= 1',
      passive: [{ type: 'divideCost', target: 'global', value: '1.25' }],
    },
    {
      id: 'rdzen.kadra_dyrektor_zjednoczenia',
      name: 'Dyrektor zjednoczenia',
      archetype: 'Aparat',
      flavor: 'Pod nim kilka kombinatów i jeden wielki telefon. Wskaźniki rosną, zanim podniesie słuchawkę.',
      costResource: 'cykle',
      cost: '120000000',
      unlock: 'posiadane.osrodek >= 5',
      passive: [{ type: 'multiplyProduction', target: 'global', value: '1.35' }],
    },
  ],

  // Załatwianie / łapówki (PLAN 9.1, Faza 4A) — smarujesz przysługą za CZASOWY efekt; każda dokłada
  // ryzyko kontroli. Łapówka rzadko była gotówką: drobne sprawy idą TOWAREM (kawa/wódka/Marlboro,
  // tanio — najpierw zaopatrz się na czarnym rynku), poważniejsze KOPERTĄ z dewizami. Cztery cele.
  bribes: [
    // Magazynier — kontroluje deficytowe części → czasowo TANIEJ.
    { id: 'rdzen.lap_mag_kawa', name: 'Kawa dla magazyniera', target: 'magazynier', flavor: 'Słoik rozpuszczalnej i nagle „coś się znajdzie" na zapleczu.', cost: '2', costResource: 'kawa', risk: 8, durationSec: 60, scope: 'cost', mul: 0.7 },
    { id: 'rdzen.lap_mag_koperta', name: 'Koperta dla magazyniera', target: 'magazynier', flavor: 'Konkrety w kopercie. Magazyn otwiera się jak za dotknięciem różdżki.', cost: '80 + zasob.dewizy * 0.1', risk: 18, durationSec: 90, scope: 'cost', mul: 0.5, unlock: 'posiadane.k202 >= 1' },
    // Celnik — przepuszcza import (obejście embarga) → więcej DEWIZ.
    { id: 'rdzen.lap_cel_whisky', name: 'Whisky dla celnika', target: 'celnik', flavor: '„Johnny" przekracza granicę szybciej niż papiery. Towar też.', cost: '2', costResource: 'wodka', risk: 12, durationSec: 90, scope: 'dewizy', mul: 2 },
    { id: 'rdzen.lap_cel_koperta', name: 'Koperta dla celnika', target: 'celnik', flavor: 'Plomby? Jakie plomby. Kontener jedzie dalej.', cost: '160 + zasob.dewizy * 0.12', risk: 24, durationSec: 90, scope: 'dewizy', mul: 3, unlock: 'posiadane.spectrum >= 1' },
    // Urzędnik — przyspiesza papierologię → więcej PRODUKCJI.
    { id: 'rdzen.lap_urz_marlboro', name: 'Marlboro dla urzędnika', target: 'urzednik', flavor: 'Karton zachodnich i podanie rozpatrzone „poza kolejnością".', cost: '2', costResource: 'papierosy', risk: 10, durationSec: 60, scope: 'prod', mul: 1.5 },
    { id: 'rdzen.lap_urz_koperta', name: 'Koperta dla urzędnika', target: 'urzednik', flavor: 'Pieczątka stempluje się sama, gdy w teczce szeleści.', cost: '120 + zasob.dewizy * 0.1', risk: 20, durationSec: 90, scope: 'prod', mul: 2.5, unlock: 'posiadane.k202 >= 1' },
    // Dygnitarz — otwiera drzwi, których nie otworzą pieniądze → wzmacnia TWOJE osobiste działanie (KLIKANIE),
    // nie produkcję (to robi Urzędnik). Apex: wielki skok i duże ryzyko. Towar dla najwyższych = KONIAK.
    { id: 'rdzen.lap_dyg_koniak', name: 'Koniak dla dygnitarza', target: 'dygnitarz', flavor: 'Flaszka francuskiego i nagle masz „dojście”. Twój czyn waży tyle, co decyzja z góry.', cost: '1', costResource: 'koniak', risk: 22, durationSec: 60, scope: 'click', mul: 6, unlock: 'posiadane.odra1305 >= 1' },
    { id: 'rdzen.lap_dyg_kolacja', name: 'Kolacja z dygnitarzem', target: 'dygnitarz', flavor: 'Stół, dewizy i obietnice. Po deserze Twoje ręce robią robotę za całe ministerstwo.', cost: '300 + zasob.dewizy * 0.2', risk: 32, durationSec: 120, scope: 'click', mul: 12, unlock: 'posiadane.osrodek >= 1' },
  ],

  // Doktryny ze Zjazdu PZPR (PLAN 9.2, Faza 4B) — na każdej nowej pięciolatce wybierasz JEDNĄ linię na
  // całą rozgrywkę. Trwałe modyfikatory (jak ulepszenia), z prawdziwymi kompromisami. „Kredyty zachodnie"
  // to gierkowski boom-bust: wielki rozpęd TERAZ, ale po czasie „bomba zadłużenia" (kryzys do końca pięciolatki).
  // REGUŁA (dla siebie na przyszłość): KAŻDA nowa doktryna dostaje pole `lore` (opis historyczny) — zakładka
  // „Doktryny” w Leksykonie jest data-driven i automatycznie pokaże każdą doktrynę z rejestru. Bez `lore`
  // Leksykon spadnie na krótki `flavor`, więc dawaj lore, by wpis był pełny.
  doctrines: [
    {
      id: 'rdzen.dok_przemysl',
      name: 'Przemysł ciężki',
      axis: 'gospodarka',
      flavor: 'Plan ponad wszystko. Huty i kombinaty dymią, półki w sklepach — niekoniecznie.',
      lore: 'Stalinowski model uprzemysłowienia: stal, węgiel, stocznie i wielkie kombinaty. Nowa Huta pod Krakowem wyrasta jako sztandarowe „miasto socjalizmu". Plan sześcioletni karmi przemysł ciężki kosztem wszystkiego innego — kominy są dumą gospodarki, ale po lodówkę, buty czy meble trzeba stać w kolejce. Liczy się tona surówki, nie wygoda obywatela.',
      effects: [
        { type: 'multiplyProduction', target: 'global', value: '2' },
        { type: 'multiplyProduction', target: 'resource:dewizy', value: '0.7' },
      ],
    },
    {
      id: 'rdzen.dok_konsumpcja',
      name: 'Dobra konsumpcyjne',
      axis: 'gospodarka',
      flavor: 'Ludziom ma się żyć dostatniej. Więcej na rynek, mniej na sztandary.',
      lore: 'Linia „małej stabilizacji" spod znaku Gomułki po Październiku ’56: nieco więcej dla rynku, mniej na propagandowy rozmach. Marzeniem rodziny jest meblościanka, telewizor i Syrenka pod blokiem. Nie jest to dostatek z reklam, ale półki wyglądają znośniej, a obywatel czuje, że plan w końcu zauważył też jego kuchnię.',
      effects: [
        { type: 'multiplyProduction', target: 'resource:dewizy', value: '2.2' },
        { type: 'multiplyProduction', target: 'global', value: '0.9' },
      ],
    },
    {
      id: 'rdzen.dok_kredyty',
      name: 'Kredyty zachodnie',
      axis: 'gospodarka',
      flavor: 'Dekada Gierka: „Polska rośnie w siłę, a ludziom żyje się dostatniej" — na zachodni kredyt. Boom teraz, rachunek później.',
      lore: 'Dekada Gierka (lata 70.): gospodarka rusza na zachodnich pożyczkach i licencjach. Z taśm schodzi Fiat 126p, w sklepach pojawia się Coca-Cola i telewizory z licencji Grundiga, buduje się Trasę Łazienkowską i Dworzec Centralny. Przez kilka lat naprawdę „żyje się dostatniej" — póki nie przychodzi termin spłaty. Zadłużenie pęcznieje, a początek lat 80. przynosi kartki, puste półki i bolesny rachunek za boom.',
      effects: [{ type: 'multiplyProduction', target: 'global', value: '2.6' }],
      debt: { afterSec: 150, crisisEvent: 'rdzen.ev_kryzys_zadluzenia' },
    },
    {
      id: 'rdzen.dok_propaganda',
      name: 'Propaganda sukcesu',
      axis: 'polityka',
      flavor: 'Telewizja pokazuje wykonanie planu w 200%. Klikanie idzie raźniej, ale wszystko drożeje, gdy rzeczywistość nie nadąża.',
      lore: 'Słynna „propaganda sukcesu" ekipy Gierka: Dziennik Telewizyjny melduje wykonanie planu w 200% i otwarcie kolejnej fabryki, gdy w sklepie stoi tylko ocet i musztarda. Entuzjazm jest na pokaz — transparenty, dożynki, akademie ku czci. Obraz w telewizorze coraz mocniej rozjeżdża się z kolejką pod sklepem, a im dłużej trwa ta gra pozorów, tym drożej kosztuje utrzymanie fasady.',
      effects: [
        { type: 'multiplyProduction', target: 'global', value: '1.6' },
        { type: 'addFlat', target: 'global', value: '50' },
        { type: 'multiplyCost', target: 'global', value: '1.3' },
      ],
    },
    {
      id: 'rdzen.dok_liberalizacja',
      name: 'Liberalizacja',
      axis: 'polityka',
      flavor: 'Trochę luzu: prywatna inicjatywa, cieplejszy czarny rynek. Taniej i więcej dewiz, bez fajerwerków.',
      lore: 'Reformy schyłku PRL (po 1982, „drugi etap reformy gospodarczej"): państwo przymyka oko na prywatną inicjatywę. Rośnie rzemiosło, firmy polonijne, prywatne warsztaty i badylarze, a cinkciarz pod Pewexem działa niemal jawnie. Nie ma fajerwerków wielkiego planu, ale rynek oddycha: jest taniej, krąży więcej towaru i twardej waluty. To już zapowiedź końca gospodarki wyłącznie sterowanej z centrali.',
      effects: [
        { type: 'divideCost', target: 'global', value: '1.25' },
        { type: 'multiplyProduction', target: 'resource:dewizy', value: '1.4' },
      ],
    },
    // Więcej doktryn (U5) — kolejne linie do wyboru na Zjeździe, każda z realnym kompromisem i `lore`.
    {
      id: 'rdzen.dok_autarkia',
      name: 'Samowystarczalność',
      axis: 'gospodarka',
      flavor: 'Wszystko swoje, nic z importu. Taniej i pewniej — ale o twardą walutę trudniej.',
      lore: 'Linia opierania się „na własnych siłach": substytucja importu, krajowe odpowiedniki zachodnich licencji, „polskie" wszystko — od fiata po komputer. Mniej zależności od kaprysów Zachodu i kursu dolara, produkcja kręci się tanim, miejscowym kosztem. Cena: odcięcie od dewiz i technologii zza żelaznej kurtyny, więc twarda waluta sączy się cienką strużką, a postęp goni resztę świata zadyszany.',
      effects: [
        { type: 'divideCost', target: 'global', value: '1.4' },
        { type: 'multiplyProduction', target: 'resource:dewizy', value: '0.6' },
      ],
    },
    {
      id: 'rdzen.dok_eksport',
      name: 'Eksport za wszelką cenę',
      axis: 'gospodarka',
      flavor: 'Wszystko, co najlepsze, jedzie na Zachód po dewizy. Krajowy rynek dostaje resztki.',
      lore: 'Pogoń za dewizami na spłatę długu: najlepsze towary — szynka, meble, statki — płyną na eksport, a w kraju zostają puste haki i ocet. „Manewr gospodarczy" przełomu dekad: liczy się bilans handlowy, nie sklepowa półka. Strumień twardej waluty robi się rwący, ale krajowa produkcja na potrzeby obywatela jest dławiona, bo wszystko, co da się sprzedać za zielone, znika z rynku wewnętrznego.',
      effects: [
        { type: 'multiplyProduction', target: 'resource:dewizy', value: '2.6' },
        { type: 'multiplyProduction', target: 'global', value: '0.85' },
      ],
    },
  ],

  // Dyplomacja bloków (PLAN 9.3, Faza 4C) — relacja z krajem PRZESUWA różne dźwignie ekonomii. Inwestujesz
  // dewizy, relacja rośnie (0..1000), bonus skaluje się z poziomem. REGUŁA (2026-07-01): w obrębie JEDNEGO
  // bloku każdy kraj ma INNĄ premię (scope); premia może się powtarzać tylko między blokami. Wschód = RWPG
  // (6 krajów), Zachód = za murem CoCom. Relacja = flaga `relacja.<id>`. Opisy powiązane z danym krajem.
  diplomacy: [
    // — Blok wschodni (RWPG): 6 krajów, każdy z INNĄ premią (cost/prod/cykle/dewizy/click/all) —
    {
      id: 'zsrr',
      name: 'ZSRR',
      bloc: 'wschod',
      flavor: 'Wielki brat. Radziecka ropa i gaz płyną rurociągiem „Przyjaźń" po cenach poniżej światowych — tania energia, choć pod czujnym okiem Moskwy.',
      benefit: 'Tania radziecka energia — niższe koszty wszystkiego.',
      scope: 'cost',
      perPoint: 0.0003,
      cost: '40 + tempo.dewizy * 4',
    },
    {
      id: 'czechoslowacja',
      name: 'Czechosłowacja',
      bloc: 'wschod',
      flavor: 'Bratni sąsiad z porządnym przemysłem: Škoda, tramwaje Tatra, elektronika Tesla. Solidne maszyny i podzespoły zza południowej granicy.',
      benefit: 'Czeskie maszyny i podzespoły — wyższa produkcja.',
      scope: 'prod',
      perPoint: 0.0003,
      cost: '45 + tempo.dewizy * 4',
    },
    {
      id: 'nrd',
      name: 'NRD',
      bloc: 'wschod',
      flavor: 'Zza Odry — Robotron i jego elektronika (U880 to enerdowski klon Z80). Precyzyjne układy scalone i moc obliczeniowa spod znaku Stasi.',
      benefit: 'Elektronika Robotrona — więcej mocy obliczeniowej (cykli).',
      scope: 'cykle',
      perPoint: 0.00035,
      cost: '50 + tempo.dewizy * 5',
    },
    {
      id: 'wegry',
      name: 'Węgry',
      bloc: 'wschod',
      flavor: 'Budapeszt i „gulaszowy komunizm" — najbardziej rynkowa gospodarka bloku. Prywatne sklepiki, żywy handel i najłatwiej dostępna twarda waluta.',
      benefit: 'Żywy węgierski handel — więcej dewiz.',
      scope: 'dewizy',
      perPoint: 0.0004,
      cost: '35 + tempo.dewizy * 4',
    },
    {
      id: 'bulgaria',
      name: 'Bułgaria',
      bloc: 'wschod',
      flavor: 'Sofia dostarcza Prawce — bułgarskie klony Apple i IBM, „krzemowa dolina bloku". Komputer pod ręką sprawia, że własne ręce liczą raźniej.',
      benefit: 'Prawce pod ręką — silniejsze klikanie.',
      scope: 'click',
      perPoint: 0.0005,
      cost: '45 + tempo.dewizy * 4',
    },
    {
      id: 'kuba',
      name: 'Kuba',
      bloc: 'wschod',
      flavor: 'Hawana zza oceanu: cukier trzcinowy, rum i cygara, a nade wszystko ideologiczne braterstwo. Daleki sojusznik, który dorzuca wszystkiego po trochu.',
      benefit: 'Karaibskie braterstwo — wszystkiego po trochu (koszty ↓, produkcja ↑).',
      scope: 'all',
      perPoint: 0.0004,
      cost: '55 + tempo.dewizy * 5',
    },
    // — Zachód i sojusznicy (za murem CoCom): premie mogą powtarzać te ze Wschodu (inny blok) —
    {
      id: 'japonia',
      name: 'Japonia',
      bloc: 'zachod',
      flavor: 'Kapitalista z innej bajki, lecz przyjazny: standard MSX był japoński, a maszyny Yamaha MSX trafiały nawet do radzieckich szkół (klasy КУВТ). Elektronika najwyższej próby.',
      benefit: 'Japońska elektronika i MSX — wyższa produkcja.',
      scope: 'prod',
      perPoint: 0.0004,
      cost: '70 + tempo.dewizy * 6',
      unlock: 'posiadane.spectrum >= 1',
    },
    {
      id: 'rfn',
      name: 'RFN',
      bloc: 'zachod',
      flavor: 'Republika Federalna Niemiec — Siemens, Nixdorf, zachodnie licencje i kredyty. Technologia zza żelaznej kurtyny, jeśli tylko CoCom przymknie oko: nowocześniej i taniej.',
      benefit: 'Zachodnie licencje i kredyty RFN — niższe koszty.',
      scope: 'cost',
      perPoint: 0.00035,
      cost: '120 + tempo.dewizy * 7',
      unlock: 'posiadane.spectrum >= 1',
    },
    {
      id: 'usa',
      name: 'USA',
      bloc: 'zachod',
      flavor: 'Zakazany owoc zza muru CoCom: twarda waluta i technologia o pokolenie przed blokiem. Obejście embarga kosztuje, ale dolar płynie szerokim strumieniem.',
      benefit: 'Obejście embarga CoCom — silny dopływ dewiz.',
      scope: 'dewizy',
      perPoint: 0.0006,
      cost: '150 + tempo.dewizy * 9',
      unlock: 'posiadane.mazovia >= 1',
    },
  ],
};
